<<<<<<< HEAD
name: Deploy to VM

on:
  push:
    branches: [ main ]  # Adjust this if your primary branch has a different name
=======
name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
>>>>>>> origin/main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

<<<<<<< HEAD
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to VM
      run: |
        ssh azureuser@${{ secrets.VM_IP_ADDRESS }} 'bash -s' << EOF
          cd ~/flask-hello-world
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flask-app
        EOFx
=======
    - name: Copy files to VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "app.py"
        target: "/home/azureuser/flask-hello-world"

    - name: Execute remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart flask-app.service
>>>>>>> origin/main
